# -*- coding: utf-8 -*-
"""Aarush Soni ML project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KuGkra2bntLQUzV8z4pKQ3mkyben-qcQ

# Credit Card Credit Limit Prediction
### A Machine Learning Project
### Name - Aarush Soni

**Objective:** Predict a customer's `CREDIT_LIMIT` using their credit card usage behavior
(balance, purchases, cash advances, payments, tenure, etc.)

**Dataset:** `CC_GENERAL.csv` — 8,950 credit card holders, 18 behavioral features.

**Algorithms compared:**
1. Linear Regression (LR)
2. Decision Tree Regressor (DTR)
3. Random Forest Regressor (RF)
4. XGBoost Regressor (XGB)

**Workflow:** EDA → Data Cleaning → Feature Preparation → Model Training → Evaluation → Comparison

## 1. Import Libraries
"""

try:
    import numpy as np
except ModuleNotFoundError:
    import sys, subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "numpy"])
    import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (10, 6)

import warnings
warnings.filterwarnings('ignore')

"""## 2. Load Dataset"""

df = pd.read_csv('CC GENERAL.csv')
print("Shape:", df.shape)
df.head()

df.info()

df.describe().T

"""## 3. Exploratory Data Analysis (EDA)

### 3.1 Missing Values
"""

missing = df.isnull().sum()
missing = missing[missing > 0]
print(missing)

plt.figure(figsize=(6,4))
sns.barplot(x=missing.values, y=missing.index, color='indianred')
plt.title('Missing Values by Column')
plt.xlabel('Count of Missing Values')
plt.tight_layout()
plt.show()

"""### 3.2 Target Variable Distribution — CREDIT_LIMIT"""

plt.figure(figsize=(10,5))
sns.histplot(df['CREDIT_LIMIT'].dropna(), bins=50, kde=True, color='steelblue')
plt.title('Distribution of Credit Limit')
plt.xlabel('Credit Limit')
plt.ylabel('Frequency')
plt.show()

"""### 3.3 Correlation Heatmap"""

numeric_df = df.drop(columns=['CUST_ID'])
plt.figure(figsize=(14, 10))
corr = numeric_df.corr()
sns.heatmap(corr, annot=True, fmt='.2f', cmap='coolwarm', linewidths=0.5)
plt.title('Feature Correlation Heatmap')
plt.show()

"""### 3.4 Correlation with Target (CREDIT_LIMIT)"""

target_corr = corr['CREDIT_LIMIT'].drop('CREDIT_LIMIT').sort_values(ascending=False)
plt.figure(figsize=(8,6))
sns.barplot(x=target_corr.values, y=target_corr.index, palette='viridis')
plt.title('Feature Correlation with CREDIT_LIMIT')
plt.xlabel('Correlation Coefficient')
plt.show()
print(target_corr)

"""### 3.5 Distributions of Key Features"""

features_to_plot = ['BALANCE', 'PURCHASES', 'CASH_ADVANCE', 'PAYMENTS', 'TENURE', 'PRC_FULL_PAYMENT']

fig, axes = plt.subplots(2, 3, figsize=(18, 10))
axes = axes.flatten()
for i, col in enumerate(features_to_plot):
    sns.histplot(df[col].dropna(), bins=40, kde=True, ax=axes[i], color='teal')
    axes[i].set_title(f'Distribution of {col}')
plt.tight_layout()
plt.show()

"""### 3.6 Outlier Check with Boxplots"""

fig, axes = plt.subplots(2, 3, figsize=(18, 8))
axes = axes.flatten()
for i, col in enumerate(features_to_plot):
    sns.boxplot(x=df[col], ax=axes[i], color='salmon')
    axes[i].set_title(f'Boxplot of {col}')
plt.tight_layout()
plt.show()

"""### 3.7 Relationship Between Purchases and Credit Limit"""

plt.figure(figsize=(8,6))
sns.scatterplot(data=df, x='PURCHASES', y='CREDIT_LIMIT', alpha=0.5, color='purple')
plt.title('Purchases vs Credit Limit')
plt.show()

"""## 4. Data Cleaning & Preprocessing

- Drop `CUST_ID` (identifier, not predictive)
- Impute missing `MINIMUM_PAYMENTS` and `CREDIT_LIMIT` with median
- Split features (X) and target (y)
- Train-test split (80/20)
- Scale features for Linear Regression
"""

data = df.drop(columns=['CUST_ID']).copy()

# Impute missing values with median
data['MINIMUM_PAYMENTS'] = data['MINIMUM_PAYMENTS'].fillna(data['MINIMUM_PAYMENTS'].median())
data = data.dropna(subset=['CREDIT_LIMIT'])  # drop the 1 row missing target

print("Missing values after cleaning:")
print(data.isnull().sum().sum())

X = data.drop(columns=['CREDIT_LIMIT'])
y = data['CREDIT_LIMIT']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print("Train shape:", X_train.shape, " Test shape:", X_test.shape)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

"""## 5. Model Training

We train four regression models and evaluate each with:
- **RMSE** (Root Mean Squared Error)
- **MAE** (Mean Absolute Error)
- **R² Score** (Coefficient of Determination)

### 5.1 Decision Tree Regressor (DTR)
"""

dtr = DecisionTreeRegressor(max_depth=8, random_state=42)
dtr.fit(X_train, y_train)
dtr_pred = dtr.predict(X_test)

"""### 5.2 Random Forest Regressor (RF)"""

rf = RandomForestRegressor(n_estimators=200, max_depth=10, random_state=42, n_jobs=-1)
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)

"""### 5.3 XGBoost Regressor (XGB)"""

xgb = XGBRegressor(n_estimators=200, max_depth=6, learning_rate=0.1, random_state=42)
xgb.fit(X_train, y_train)
xgb_pred = xgb.predict(X_test)

"""### 5.4 Linear Regression (LR)"""

lr = LinearRegression()
lr.fit(X_train_scaled, y_train)
lr_pred = lr.predict(X_test_scaled)

"""## 6. Model Evaluation & Comparison"""

def evaluate(name, y_true, y_pred):
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mae = mean_absolute_error(y_true, y_pred)
    r2 = r2_score(y_true, y_pred)
    return {'Model': name, 'RMSE': rmse, 'MAE': mae, 'R2 Score': r2}

results = [
    evaluate('Linear Regression', y_test, lr_pred),
    evaluate('Decision Tree Regressor', y_test, dtr_pred),
    evaluate('Random Forest Regressor', y_test, rf_pred),
    evaluate('XGBoost Regressor', y_test, xgb_pred),
]

results_df = pd.DataFrame(results).sort_values('R2 Score', ascending=False).reset_index(drop=True)
results_df

fig, axes = plt.subplots(1, 3, figsize=(18,5))
metrics = ['RMSE', 'MAE', 'R2 Score']
colors = ['#4C72B0', '#DD8452', '#55A868']
for i, m in enumerate(metrics):
    sns.barplot(data=results_df, x='Model', y=m, ax=axes[i], color=colors[i])
    axes[i].set_title(f'{m} by Model')
    axes[i].tick_params(axis='x', rotation=30)
plt.tight_layout()
plt.show()

"""### 6.1 Actual vs Predicted (Best Model)"""

best_model_name = results_df.iloc[0]['Model']
pred_map = {
    'Linear Regression': lr_pred,
    'Decision Tree Regressor': dtr_pred,
    'Random Forest Regressor': rf_pred,
    'XGBoost Regressor': xgb_pred
}
best_pred = pred_map[best_model_name]

plt.figure(figsize=(8,7))
plt.scatter(y_test, best_pred, alpha=0.5, color='darkgreen')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
plt.xlabel('Actual Credit Limit')
plt.ylabel('Predicted Credit Limit')
plt.title(f'Actual vs Predicted — {best_model_name}')
plt.show()

print(f"Best performing model: {best_model_name}")

"""### 6.2 Feature Importance (Random Forest & XGBoost)"""

fig, axes = plt.subplots(1, 2, figsize=(16,6))

rf_importance = pd.Series(rf.feature_importances_, index=X.columns).sort_values(ascending=False)
sns.barplot(x=rf_importance.values, y=rf_importance.index, ax=axes[0], color='seagreen')
axes[0].set_title('Random Forest Feature Importance')

xgb_importance = pd.Series(xgb.feature_importances_, index=X.columns).sort_values(ascending=False)
sns.barplot(x=xgb_importance.values, y=xgb_importance.index, ax=axes[1], color='cornflowerblue')
axes[1].set_title('XGBoost Feature Importance')

plt.tight_layout()
plt.show()

"""## 7. Conclusion

- All four models were trained to predict `CREDIT_LIMIT` from customer credit card usage behavior.
- Tree-based ensemble methods (Random Forest, XGBoost) generally outperform Linear Regression on this
  dataset because the relationship between spending behavior and credit limit is non-linear.
- `PAYMENTS`, `PURCHASES`, and `BALANCE` tend to be the most influential features in predicting credit limit.
- The comparison table and charts above make it easy to justify which model is best suited for deployment,
  based on the trade-off between interpretability (Linear Regression) and accuracy (XGBoost/Random Forest).

**Possible extensions:**
- Hyperparameter tuning with GridSearchCV / RandomizedSearchCV
- Cross-validation for more robust performance estimates
- Log-transforming skewed features (e.g., BALANCE, CASH_ADVANCE) before Linear Regression
- Trying clustering (K-Means) on this dataset for customer segmentation as a separate unsupervised task
"""

